name: ya_player
description: Open source Yandex.Music player
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audio_player_gst:
    path: ../audio_player_gst
  audio_video_progress_bar: ^2.0.0
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.2
  http: ^1.1.0
  shared_preferences: ^2.3.3
  crypto: ^3.0.6
  uuid: ^4.5.1
  equatable: ^2.0.7
  collection: ^1.18.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.1
  animations: ^2.0.7
  #  bitsdojo_window: ^0.1.5
  flutter_svg: ^2.0.16
  mask_text_input_formatter: ^2.5.0
  html_character_entities: ^1.0.0+1
  meta: ^1.15.0
  dbus: ^0.7.10
  xdg_status_notifier_item: ^0.0.1
  window_manager: ^0.4.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages